name: "ArXiv HTML Content issue"
description: Testing Template!
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **TEST REPORT TEMPLATE**
        ↩ Developing.

        **Report general problem**
        🙋 [Report issue](https://github.com/YiChen8185/TestForGitHubIssue/issues/new?assignees=&labels=&projects=&title=General_Problem&template=bug_report.yml&articleTitle=GeneralProblem)

        **Problem**
        ‼️ Chrome may disable the accsess to open new windows, and users will need to manually allow it.

        ---

  - type: textarea
    id: extra-info
    attributes:
      label: (Optional) Please add any additional info about this issue
      description: For example the steps to reproduce a bug or screenshots.

  - type: dropdown
    id: problem-type
    attributes:
      label: (Required) What is this issue most closely related to? Select one.
      options:
        - Math
        - Figures
        - References
        - Other
    validations:
      required: true

  - type: dropdown
    id: screenReader-device
    attributes:
      label: (Optional) If you use a screen reader, which one do you use? Select one.
      options:
        - NVDA
        - JAWS
        - VoiceOver
        - Other

  - type: input
    id: other-sr
    attributes:
      label: (Optional) Other screen reader
      description: If you selected 'other', what screen reader or text-to-speech software do you use?

  # Below is autofill section.
  #DO WE NEED ALL OF THESE HTML BREAKS?
  - type: markdown
    attributes:
      value: |
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        # The following data is set automatically. It can help with troubleshooting reported issues. Do not modify.

# WHAT IS THIS ONE? IS THIS WHERE THE USER'S ORIGINAL DESCRIPTION IS CAPTURED?
  - type: input
    id: description
    attributes:
      description: Set automatically. Do not modify.
      label: Description
    validations:
      required: true

  - type: input
    id: uniqueId
    attributes:
      label: Internal unique ID
      description: Set automatically. Do not modify.
    validations:
      required: true

  - type: input
    id: fullUrl
    attributes:
      label: Paper URL
      description: Set automatically. Do not modify.
    validations:
      required: true

  - type: input
    id: arxivId
    attributes:
      label: arXiv Id
      description: Set automatically. Do not modify.
    validations:
      required: true

  - type: input
    id: browserInfo
    attributes:
      label: Browser
      description: Set automatically. Do not modify.
    validations:
      required: true

  - type: input
    id: deviceType
    attributes:
      label: Device Type
      description: Set automatically. Do not modify.
    validations:
      required: true
