name: "ArXiv HTML Content issue"
description: Testing Template!
body:
  - type: markdown
    attributes:
      value: Review and add any new information before submitting your issue report.

  - type: input
    id: description
    attributes:
      description: User description
      label: Description
    validations:
      required: true

  - type: textarea
    id: extra-info
    attributes:
      label: (Optional) Please add any additional info about this issue
      description: For example the steps to reproduce a bug or screenshots.

  - type: dropdown
    id: problem-type
    attributes:
      label: (Required) What is this issue most closely related to? Select one.
      options:
        - Math
        - Figures
        - References
        - Other
    validations:
      required: true
    #ADD TO INITIAL MODAL INSTEAD, SO WE GET THIS INFO EVEN IF THEY SUBMIT WITHOUT GITHUB
  # - type: dropdown
  #   id: screenReader-device
  #   attributes:
  #     label: (Optional) If you use a screen reader, which one do you use? Select one.
  #     options:
  #       - NVDA
  #       - JAWS
  #       - VoiceOver
  #       - Other
  #
  # - type: input
  #   id: other-sr
  #   attributes:
  #     label: (Optional) Other screen reader
  #     description: If you selected 'other', what screen reader or text-to-speech software do you use?

  ---

  # Below is autofill section.
  - type: markdown
    attributes:
      value: The following data is collected automatically to help with troubleshooting. Do not modify.

  - type: input
    id: uniqueId
    attributes:
      label: Internal issue ID
      description: Set automatically. Do not modify.
    validations:
      required: true

  - type: input
    id: fullUrl
    attributes:
      label: Paper URL
      description: Set automatically. Do not modify.
    validations:
      required: true

#CAN WE HIDE THESE, BUT STILL HAVE THEM WRITE TO THE TICKET?
  - type: input
    id: browserInfo
    attributes:
      label: Browser
      description: Set automatically. Do not modify.
    validations:
      required: true

  - type: input
    id: deviceType
    attributes:
      label: Device Type
      description: Set automatically. Do not modify.
    validations:
      required: true
